# =========================================
# APPLICATION CORE SETTINGS
# =========================================
erfinder:
  login:
    max-attempts-in-period: 10
    clear-attempt-after-minutes: 30
    timeout-period-minutes: 300

# Server HTTP Properties
server:
  forward-headers-strategy: framework
  port: 8080


# =========================================
# SPRING BOOT CONFIGURATION
# =========================================
spring:
  main:
    banner-mode: off
  application:
    name: erfinder

  # SMTP Email Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ERFinderServicesT7@gmail.com"
    password: "cpnt ezcf otfl wezl" ## "ERFinderServicesT34M7"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Database Connection String
  datasource:
    url: jdbc:mysql://erfinder-erfinder.k.aivencloud.com:26268/defaultdb?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_2kwhLT7ZoRaVQ6GpXiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update

  # Local Development Tools
  devtools:
    restart:
      additional-exclude: launcherDir/**
    add-properties: false

  # JSON Serialization Rules
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

  # Console Formatting
  output:
    ansi:
      enabled: detect

  # File Upload Limits
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Static Web Resources
  web:
    resources:
      static-locations: classpath:/launcherDir/,classpath:/public/
    error:
      whitelabel:
        enabled: false
      path: /error

debug: false


# =========================================
# SYSTEM LOGGING RULES
# =========================================
logging:
  level:
    web: info
    root: info

  # Log Format Patterns
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'