
# Application Configuration Properties
erfinder:
  login:
    max-attempts-in-period: 10
    clear-attempt-after-minutes: 30
    timeout-period-minutes: 300

# Server Properties
server:
  forward-headers-strategy: framework
  port: 8080

# Spring Boot Configuration
spring:
  main:
    banner-mode: off
  application:
    name: erfinder

  # Database Connection Settings
  datasource:
    url: jdbc:mysql://erfinder-erfinder.k.aivencloud.com:26268/defaultdb?sslMode=REQUIRED
    username: avnadmin
    password: AVNS_2kwhLT7ZoRaVQ6GpXiz
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update

  # Development Tools
  devtools:
    restart:
      additional-exclude: launcherDir/**
    add-properties: false

  # Serialization
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

  # Console Output
  output:
    ansi:
      enabled: detect

  # File Upload Limits
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Web Resource Handling
  web:
    resources:
      static-locations: classpath:/launcherDir/,classpath:/public/
    error:
      whitelabel:
        enabled: false
      path: /error

debug: false

# Logging Configuration
logging:
  level:
    web: info
    root: info

  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'